/********************************************************************************
** Form generated from reading UI file 'game_mainpage.ui'
**
** Created by: Qt User Interface Compiler version 6.4.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_GAME_MAINPAGE_H
#define UI_GAME_MAINPAGE_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Game_MainPage
{
public:
    QWidget *centralwidget;
    QPushButton *pushButton_Touxiang;
    QLabel *label_name;
    QLabel *label_level;
    QLabel *label_Gold;
    QPushButton *pushButton_Dianquan;
    QPushButton *pushButton_Email;
    QPushButton *pushButton_Settings;
    QPushButton *pushButton_StratGame;
    QPushButton *pushButton_Task;
    QPushButton *pushButton_Shopping;
    QPushButton *pushButton_Choujiang;
    QPushButton *pushButton_Pet;
    QPushButton *pushButton_Store;
    QPushButton *pushButton_PrepareForWar;
    QPushButton *pushButton_13;
    QTextEdit *textEdit_chat;
    QPushButton *pushButton_SendChatmsg;
    QLineEdit *lineEdit_ChatmsgMychat;
    QPushButton *pushButton_ShowChatMsg;
    QSlider *verticalSlider;
    QPushButton *pushButton_ChatTouxiang1;
    QLineEdit *lineEdit_Chatmsg1;
    QPushButton *pushButton_ChatTouxiang2;
    QPushButton *pushButton_ChatTouxiang3;
    QPushButton *pushButton_ChatTouxiang4;
    QLineEdit *lineEdit_Chatmsg2;
    QLineEdit *lineEdit_Chatmsg3;
    QLineEdit *lineEdit_Chatmsg4;
    QPushButton *pushButton_ChatTouxiang1_2;
    QPushButton *pushButton_ChatTouxiang2_2;
    QPushButton *pushButton_ChatTouxiang3_2;
    QPushButton *pushButton_ChatTouxiang4_2;
    QLineEdit *lineEdit_Chatname1;
    QLineEdit *lineEdit_Chatname2;
    QLineEdit *lineEdit_Chatname3;
    QLineEdit *lineEdit_Chatname4;
    QPushButton *pushButton_ChatTouxiang5;
    QPushButton *pushButton_ChatTouxiang6;
    QPushButton *pushButton_ChatTouxiang5_2;
    QPushButton *pushButton_ChatTouxiang6_2;
    QLineEdit *lineEdit_Chatmsg5;
    QLineEdit *lineEdit_Chatmsg6;
    QLineEdit *lineEdit_Chatname5;
    QLineEdit *lineEdit_Chatname6;
    QTextEdit *textEdit_StartRoom;
    QPushButton *pushButton_CreateRoom;
    QPushButton *pushButton_Join_Room;
    QPushButton *pushButton_JoinRandomRoom;
    QPushButton *pushButton_Room_back;
    QLineEdit *lineEdit_CreateRoom;
    QLabel *label_CreateRoomName;
    QLabel *label_CreateRoomFlag;
    QComboBox *comboBox_CreateRoomFlag;
    QLabel *label_CreateRoomPasswd;
    QLineEdit *lineEdit_CreateRoomPasswd;
    QLabel *label_CreateRoomDescription;
    QLineEdit *lineEdit_CreateRoomDescription;
    QPushButton *pushButton_CreateRoomShow;
    QPushButton *pushButton_CreateRoomBack;

    void setupUi(QMainWindow *Game_MainPage)
    {
        if (Game_MainPage->objectName().isEmpty())
            Game_MainPage->setObjectName("Game_MainPage");
        Game_MainPage->resize(1400, 900);
        QFont font;
        font.setPointSize(11);
        Game_MainPage->setFont(font);
        Game_MainPage->setCursor(QCursor(Qt::ArrowCursor));
        centralwidget = new QWidget(Game_MainPage);
        centralwidget->setObjectName("centralwidget");
        pushButton_Touxiang = new QPushButton(centralwidget);
        pushButton_Touxiang->setObjectName("pushButton_Touxiang");
        pushButton_Touxiang->setGeometry(QRect(0, 0, 100, 100));
        label_name = new QLabel(centralwidget);
        label_name->setObjectName("label_name");
        label_name->setGeometry(QRect(100, 0, 161, 51));
        QFont font1;
        font1.setPointSize(15);
        label_name->setFont(font1);
        label_name->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_level = new QLabel(centralwidget);
        label_level->setObjectName("label_level");
        label_level->setGeometry(QRect(100, 60, 101, 21));
        QFont font2;
        font2.setPointSize(12);
        label_level->setFont(font2);
        label_level->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_Gold = new QLabel(centralwidget);
        label_Gold->setObjectName("label_Gold");
        label_Gold->setGeometry(QRect(900, 0, 131, 35));
        label_Gold->setAlignment(Qt::AlignCenter);
        pushButton_Dianquan = new QPushButton(centralwidget);
        pushButton_Dianquan->setObjectName("pushButton_Dianquan");
        pushButton_Dianquan->setGeometry(QRect(1050, 0, 111, 35));
        pushButton_Email = new QPushButton(centralwidget);
        pushButton_Email->setObjectName("pushButton_Email");
        pushButton_Email->setGeometry(QRect(1200, 0, 80, 35));
        pushButton_Settings = new QPushButton(centralwidget);
        pushButton_Settings->setObjectName("pushButton_Settings");
        pushButton_Settings->setGeometry(QRect(1300, 0, 100, 35));
        pushButton_StratGame = new QPushButton(centralwidget);
        pushButton_StratGame->setObjectName("pushButton_StratGame");
        pushButton_StratGame->setGeometry(QRect(1200, 700, 200, 200));
        pushButton_StratGame->setMinimumSize(QSize(200, 200));
        pushButton_StratGame->setMaximumSize(QSize(200, 200));
        QFont font3;
        font3.setPointSize(21);
        pushButton_StratGame->setFont(font3);
        pushButton_Task = new QPushButton(centralwidget);
        pushButton_Task->setObjectName("pushButton_Task");
        pushButton_Task->setGeometry(QRect(120, 770, 170, 130));
        QFont font4;
        font4.setPointSize(13);
        font4.setBold(true);
        font4.setUnderline(true);
        pushButton_Task->setFont(font4);
        pushButton_Task->setFlat(true);
        pushButton_Shopping = new QPushButton(centralwidget);
        pushButton_Shopping->setObjectName("pushButton_Shopping");
        pushButton_Shopping->setGeometry(QRect(290, 770, 170, 130));
        pushButton_Shopping->setFont(font4);
        pushButton_Shopping->setFlat(true);
        pushButton_Choujiang = new QPushButton(centralwidget);
        pushButton_Choujiang->setObjectName("pushButton_Choujiang");
        pushButton_Choujiang->setGeometry(QRect(460, 770, 170, 130));
        pushButton_Choujiang->setFont(font4);
        pushButton_Choujiang->setFlat(true);
        pushButton_Pet = new QPushButton(centralwidget);
        pushButton_Pet->setObjectName("pushButton_Pet");
        pushButton_Pet->setGeometry(QRect(630, 770, 170, 130));
        QFont font5;
        font5.setPointSize(13);
        font5.setBold(true);
        font5.setItalic(false);
        font5.setUnderline(true);
        font5.setStrikeOut(false);
        font5.setKerning(false);
        pushButton_Pet->setFont(font5);
        pushButton_Pet->setFlat(true);
        pushButton_Store = new QPushButton(centralwidget);
        pushButton_Store->setObjectName("pushButton_Store");
        pushButton_Store->setGeometry(QRect(800, 770, 170, 130));
        pushButton_Store->setFont(font4);
        pushButton_Store->setFlat(true);
        pushButton_PrepareForWar = new QPushButton(centralwidget);
        pushButton_PrepareForWar->setObjectName("pushButton_PrepareForWar");
        pushButton_PrepareForWar->setGeometry(QRect(970, 770, 170, 130));
        pushButton_PrepareForWar->setFont(font4);
        pushButton_PrepareForWar->setFlat(true);
        pushButton_13 = new QPushButton(centralwidget);
        pushButton_13->setObjectName("pushButton_13");
        pushButton_13->setGeometry(QRect(0, 210, 151, 71));
        textEdit_chat = new QTextEdit(centralwidget);
        textEdit_chat->setObjectName("textEdit_chat");
        textEdit_chat->setGeometry(QRect(0, 295, 391, 321));
        QFont font6;
        font6.setPointSize(14);
        textEdit_chat->setFont(font6);
        textEdit_chat->setReadOnly(true);
        pushButton_SendChatmsg = new QPushButton(centralwidget);
        pushButton_SendChatmsg->setObjectName("pushButton_SendChatmsg");
        pushButton_SendChatmsg->setGeometry(QRect(310, 625, 81, 51));
        QFont font7;
        font7.setPointSize(11);
        font7.setBold(true);
        font7.setItalic(false);
        pushButton_SendChatmsg->setFont(font7);
        pushButton_SendChatmsg->setFlat(true);
        lineEdit_ChatmsgMychat = new QLineEdit(centralwidget);
        lineEdit_ChatmsgMychat->setObjectName("lineEdit_ChatmsgMychat");
        lineEdit_ChatmsgMychat->setGeometry(QRect(70, 630, 231, 41));
        QPalette palette;
        QBrush brush(QColor(255, 255, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        QBrush brush1(QColor(120, 120, 120, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        lineEdit_ChatmsgMychat->setPalette(palette);
        QFont font8;
        font8.setPointSize(6);
        lineEdit_ChatmsgMychat->setFont(font8);
        lineEdit_ChatmsgMychat->setAlignment(Qt::AlignCenter);
        pushButton_ShowChatMsg = new QPushButton(centralwidget);
        pushButton_ShowChatMsg->setObjectName("pushButton_ShowChatMsg");
        pushButton_ShowChatMsg->setGeometry(QRect(0, 630, 61, 41));
        QFont font9;
        font9.setPointSize(7);
        pushButton_ShowChatMsg->setFont(font9);
        verticalSlider = new QSlider(centralwidget);
        verticalSlider->setObjectName("verticalSlider");
        verticalSlider->setGeometry(QRect(420, 300, 21, 311));
        verticalSlider->setCursor(QCursor(Qt::IBeamCursor));
        verticalSlider->setMaximum(10);
        verticalSlider->setOrientation(Qt::Vertical);
        pushButton_ChatTouxiang1 = new QPushButton(centralwidget);
        pushButton_ChatTouxiang1->setObjectName("pushButton_ChatTouxiang1");
        pushButton_ChatTouxiang1->setGeometry(QRect(0, 310, 45, 45));
        pushButton_ChatTouxiang1->setFlat(true);
        lineEdit_Chatmsg1 = new QLineEdit(centralwidget);
        lineEdit_Chatmsg1->setObjectName("lineEdit_Chatmsg1");
        lineEdit_Chatmsg1->setGeometry(QRect(60, 325, 300, 20));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        lineEdit_Chatmsg1->setPalette(palette1);
        lineEdit_Chatmsg1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lineEdit_Chatmsg1->setReadOnly(true);
        pushButton_ChatTouxiang2 = new QPushButton(centralwidget);
        pushButton_ChatTouxiang2->setObjectName("pushButton_ChatTouxiang2");
        pushButton_ChatTouxiang2->setGeometry(QRect(0, 360, 45, 45));
        pushButton_ChatTouxiang2->setFlat(true);
        pushButton_ChatTouxiang3 = new QPushButton(centralwidget);
        pushButton_ChatTouxiang3->setObjectName("pushButton_ChatTouxiang3");
        pushButton_ChatTouxiang3->setGeometry(QRect(0, 410, 45, 45));
        pushButton_ChatTouxiang3->setFlat(true);
        pushButton_ChatTouxiang4 = new QPushButton(centralwidget);
        pushButton_ChatTouxiang4->setObjectName("pushButton_ChatTouxiang4");
        pushButton_ChatTouxiang4->setGeometry(QRect(0, 460, 45, 45));
        pushButton_ChatTouxiang4->setFlat(true);
        lineEdit_Chatmsg2 = new QLineEdit(centralwidget);
        lineEdit_Chatmsg2->setObjectName("lineEdit_Chatmsg2");
        lineEdit_Chatmsg2->setGeometry(QRect(60, 375, 300, 20));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        lineEdit_Chatmsg2->setPalette(palette2);
        lineEdit_Chatmsg2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lineEdit_Chatmsg2->setReadOnly(true);
        lineEdit_Chatmsg3 = new QLineEdit(centralwidget);
        lineEdit_Chatmsg3->setObjectName("lineEdit_Chatmsg3");
        lineEdit_Chatmsg3->setGeometry(QRect(60, 425, 300, 20));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        lineEdit_Chatmsg3->setPalette(palette3);
        lineEdit_Chatmsg3->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lineEdit_Chatmsg3->setReadOnly(true);
        lineEdit_Chatmsg4 = new QLineEdit(centralwidget);
        lineEdit_Chatmsg4->setObjectName("lineEdit_Chatmsg4");
        lineEdit_Chatmsg4->setGeometry(QRect(60, 475, 300, 20));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::Text, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        lineEdit_Chatmsg4->setPalette(palette4);
        lineEdit_Chatmsg4->setLayoutDirection(Qt::LeftToRight);
        lineEdit_Chatmsg4->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lineEdit_Chatmsg4->setReadOnly(true);
        pushButton_ChatTouxiang1_2 = new QPushButton(centralwidget);
        pushButton_ChatTouxiang1_2->setObjectName("pushButton_ChatTouxiang1_2");
        pushButton_ChatTouxiang1_2->setGeometry(QRect(370, 310, 45, 45));
        pushButton_ChatTouxiang1_2->setFlat(true);
        pushButton_ChatTouxiang2_2 = new QPushButton(centralwidget);
        pushButton_ChatTouxiang2_2->setObjectName("pushButton_ChatTouxiang2_2");
        pushButton_ChatTouxiang2_2->setGeometry(QRect(370, 360, 45, 45));
        pushButton_ChatTouxiang2_2->setFlat(true);
        pushButton_ChatTouxiang3_2 = new QPushButton(centralwidget);
        pushButton_ChatTouxiang3_2->setObjectName("pushButton_ChatTouxiang3_2");
        pushButton_ChatTouxiang3_2->setGeometry(QRect(370, 410, 45, 45));
        pushButton_ChatTouxiang3_2->setFlat(true);
        pushButton_ChatTouxiang4_2 = new QPushButton(centralwidget);
        pushButton_ChatTouxiang4_2->setObjectName("pushButton_ChatTouxiang4_2");
        pushButton_ChatTouxiang4_2->setGeometry(QRect(370, 460, 45, 45));
        pushButton_ChatTouxiang4_2->setFlat(true);
        lineEdit_Chatname1 = new QLineEdit(centralwidget);
        lineEdit_Chatname1->setObjectName("lineEdit_Chatname1");
        lineEdit_Chatname1->setGeometry(QRect(60, 300, 70, 20));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::Text, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        lineEdit_Chatname1->setPalette(palette5);
        lineEdit_Chatname1->setFont(font9);
        lineEdit_Chatname1->setAlignment(Qt::AlignCenter);
        lineEdit_Chatname2 = new QLineEdit(centralwidget);
        lineEdit_Chatname2->setObjectName("lineEdit_Chatname2");
        lineEdit_Chatname2->setGeometry(QRect(60, 350, 70, 20));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::Text, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        lineEdit_Chatname2->setPalette(palette6);
        lineEdit_Chatname2->setFont(font9);
        lineEdit_Chatname2->setAlignment(Qt::AlignCenter);
        lineEdit_Chatname3 = new QLineEdit(centralwidget);
        lineEdit_Chatname3->setObjectName("lineEdit_Chatname3");
        lineEdit_Chatname3->setGeometry(QRect(60, 400, 70, 20));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::Text, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        lineEdit_Chatname3->setPalette(palette7);
        lineEdit_Chatname3->setFont(font9);
        lineEdit_Chatname3->setAlignment(Qt::AlignCenter);
        lineEdit_Chatname4 = new QLineEdit(centralwidget);
        lineEdit_Chatname4->setObjectName("lineEdit_Chatname4");
        lineEdit_Chatname4->setGeometry(QRect(60, 450, 70, 20));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::Text, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        lineEdit_Chatname4->setPalette(palette8);
        lineEdit_Chatname4->setFont(font9);
        lineEdit_Chatname4->setAlignment(Qt::AlignCenter);
        pushButton_ChatTouxiang5 = new QPushButton(centralwidget);
        pushButton_ChatTouxiang5->setObjectName("pushButton_ChatTouxiang5");
        pushButton_ChatTouxiang5->setGeometry(QRect(0, 510, 45, 45));
        pushButton_ChatTouxiang5->setFlat(true);
        pushButton_ChatTouxiang6 = new QPushButton(centralwidget);
        pushButton_ChatTouxiang6->setObjectName("pushButton_ChatTouxiang6");
        pushButton_ChatTouxiang6->setGeometry(QRect(0, 560, 45, 45));
        pushButton_ChatTouxiang6->setFlat(true);
        pushButton_ChatTouxiang5_2 = new QPushButton(centralwidget);
        pushButton_ChatTouxiang5_2->setObjectName("pushButton_ChatTouxiang5_2");
        pushButton_ChatTouxiang5_2->setGeometry(QRect(370, 510, 45, 45));
        pushButton_ChatTouxiang5_2->setFlat(true);
        pushButton_ChatTouxiang6_2 = new QPushButton(centralwidget);
        pushButton_ChatTouxiang6_2->setObjectName("pushButton_ChatTouxiang6_2");
        pushButton_ChatTouxiang6_2->setGeometry(QRect(370, 560, 45, 45));
        pushButton_ChatTouxiang6_2->setFlat(true);
        lineEdit_Chatmsg5 = new QLineEdit(centralwidget);
        lineEdit_Chatmsg5->setObjectName("lineEdit_Chatmsg5");
        lineEdit_Chatmsg5->setGeometry(QRect(60, 525, 300, 20));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::Text, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        lineEdit_Chatmsg5->setPalette(palette9);
        lineEdit_Chatmsg5->setLayoutDirection(Qt::LeftToRight);
        lineEdit_Chatmsg5->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lineEdit_Chatmsg5->setReadOnly(true);
        lineEdit_Chatmsg6 = new QLineEdit(centralwidget);
        lineEdit_Chatmsg6->setObjectName("lineEdit_Chatmsg6");
        lineEdit_Chatmsg6->setGeometry(QRect(60, 575, 300, 20));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::Text, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        lineEdit_Chatmsg6->setPalette(palette10);
        lineEdit_Chatmsg6->setLayoutDirection(Qt::LeftToRight);
        lineEdit_Chatmsg6->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lineEdit_Chatmsg6->setReadOnly(true);
        lineEdit_Chatname5 = new QLineEdit(centralwidget);
        lineEdit_Chatname5->setObjectName("lineEdit_Chatname5");
        lineEdit_Chatname5->setGeometry(QRect(60, 500, 70, 20));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::Text, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        lineEdit_Chatname5->setPalette(palette11);
        lineEdit_Chatname5->setFont(font9);
        lineEdit_Chatname5->setAlignment(Qt::AlignCenter);
        lineEdit_Chatname6 = new QLineEdit(centralwidget);
        lineEdit_Chatname6->setObjectName("lineEdit_Chatname6");
        lineEdit_Chatname6->setGeometry(QRect(60, 550, 70, 20));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::Text, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        lineEdit_Chatname6->setPalette(palette12);
        lineEdit_Chatname6->setFont(font9);
        lineEdit_Chatname6->setAlignment(Qt::AlignCenter);
        textEdit_StartRoom = new QTextEdit(centralwidget);
        textEdit_StartRoom->setObjectName("textEdit_StartRoom");
        textEdit_StartRoom->setGeometry(QRect(350, 150, 700, 600));
        textEdit_StartRoom->setReadOnly(true);
        pushButton_CreateRoom = new QPushButton(centralwidget);
        pushButton_CreateRoom->setObjectName("pushButton_CreateRoom");
        pushButton_CreateRoom->setGeometry(QRect(350, 350, 220, 200));
        QFont font10;
        font10.setPointSize(20);
        pushButton_CreateRoom->setFont(font10);
        pushButton_CreateRoom->setFlat(true);
        pushButton_Join_Room = new QPushButton(centralwidget);
        pushButton_Join_Room->setObjectName("pushButton_Join_Room");
        pushButton_Join_Room->setGeometry(QRect(590, 350, 220, 200));
        pushButton_Join_Room->setFont(font10);
        pushButton_Join_Room->setFlat(true);
        pushButton_JoinRandomRoom = new QPushButton(centralwidget);
        pushButton_JoinRandomRoom->setObjectName("pushButton_JoinRandomRoom");
        pushButton_JoinRandomRoom->setGeometry(QRect(830, 350, 220, 200));
        pushButton_JoinRandomRoom->setFont(font10);
        pushButton_JoinRandomRoom->setFlat(true);
        pushButton_Room_back = new QPushButton(centralwidget);
        pushButton_Room_back->setObjectName("pushButton_Room_back");
        pushButton_Room_back->setGeometry(QRect(870, 160, 161, 71));
        QFont font11;
        font11.setPointSize(18);
        pushButton_Room_back->setFont(font11);
        lineEdit_CreateRoom = new QLineEdit(centralwidget);
        lineEdit_CreateRoom->setObjectName("lineEdit_CreateRoom");
        lineEdit_CreateRoom->setGeometry(QRect(680, 250, 350, 60));
        lineEdit_CreateRoom->setFont(font1);
        lineEdit_CreateRoom->setAlignment(Qt::AlignCenter);
        label_CreateRoomName = new QLabel(centralwidget);
        label_CreateRoomName->setObjectName("label_CreateRoomName");
        label_CreateRoomName->setGeometry(QRect(360, 240, 311, 71));
        label_CreateRoomName->setFont(font1);
        label_CreateRoomName->setAlignment(Qt::AlignCenter);
        label_CreateRoomFlag = new QLabel(centralwidget);
        label_CreateRoomFlag->setObjectName("label_CreateRoomFlag");
        label_CreateRoomFlag->setGeometry(QRect(360, 350, 311, 71));
        label_CreateRoomFlag->setFont(font1);
        label_CreateRoomFlag->setAlignment(Qt::AlignCenter);
        comboBox_CreateRoomFlag = new QComboBox(centralwidget);
        comboBox_CreateRoomFlag->setObjectName("comboBox_CreateRoomFlag");
        comboBox_CreateRoomFlag->setGeometry(QRect(680, 360, 350, 50));
        comboBox_CreateRoomFlag->setFont(font1);
        label_CreateRoomPasswd = new QLabel(centralwidget);
        label_CreateRoomPasswd->setObjectName("label_CreateRoomPasswd");
        label_CreateRoomPasswd->setGeometry(QRect(360, 460, 311, 71));
        label_CreateRoomPasswd->setFont(font1);
        label_CreateRoomPasswd->setAlignment(Qt::AlignCenter);
        lineEdit_CreateRoomPasswd = new QLineEdit(centralwidget);
        lineEdit_CreateRoomPasswd->setObjectName("lineEdit_CreateRoomPasswd");
        lineEdit_CreateRoomPasswd->setGeometry(QRect(680, 470, 350, 60));
        lineEdit_CreateRoomPasswd->setFont(font1);
        lineEdit_CreateRoomPasswd->setAlignment(Qt::AlignCenter);
        label_CreateRoomDescription = new QLabel(centralwidget);
        label_CreateRoomDescription->setObjectName("label_CreateRoomDescription");
        label_CreateRoomDescription->setGeometry(QRect(360, 580, 311, 71));
        label_CreateRoomDescription->setFont(font1);
        label_CreateRoomDescription->setAlignment(Qt::AlignCenter);
        lineEdit_CreateRoomDescription = new QLineEdit(centralwidget);
        lineEdit_CreateRoomDescription->setObjectName("lineEdit_CreateRoomDescription");
        lineEdit_CreateRoomDescription->setGeometry(QRect(680, 590, 350, 60));
        lineEdit_CreateRoomDescription->setFont(font1);
        lineEdit_CreateRoomDescription->setAlignment(Qt::AlignCenter);
        pushButton_CreateRoomShow = new QPushButton(centralwidget);
        pushButton_CreateRoomShow->setObjectName("pushButton_CreateRoomShow");
        pushButton_CreateRoomShow->setGeometry(QRect(470, 670, 121, 51));
        pushButton_CreateRoomBack = new QPushButton(centralwidget);
        pushButton_CreateRoomBack->setObjectName("pushButton_CreateRoomBack");
        pushButton_CreateRoomBack->setGeometry(QRect(800, 670, 121, 51));
        Game_MainPage->setCentralWidget(centralwidget);

        retranslateUi(Game_MainPage);

        pushButton_ChatTouxiang4_2->setDefault(false);


        QMetaObject::connectSlotsByName(Game_MainPage);
    } // setupUi

    void retranslateUi(QMainWindow *Game_MainPage)
    {
        Game_MainPage->setWindowTitle(QCoreApplication::translate("Game_MainPage", "MainWindow", nullptr));
        pushButton_Touxiang->setText(QString());
        label_name->setText(QCoreApplication::translate("Game_MainPage", "\347\216\251\345\256\266\345\247\223\345\220\215", nullptr));
        label_level->setText(QCoreApplication::translate("Game_MainPage", "\347\255\211\347\272\247", nullptr));
        label_Gold->setText(QCoreApplication::translate("Game_MainPage", "50", nullptr));
        pushButton_Dianquan->setText(QCoreApplication::translate("Game_MainPage", "\347\202\271\345\210\270", nullptr));
        pushButton_Email->setText(QCoreApplication::translate("Game_MainPage", "\351\202\256\344\273\266", nullptr));
        pushButton_Settings->setText(QCoreApplication::translate("Game_MainPage", "\350\256\276\347\275\256", nullptr));
        pushButton_StratGame->setText(QString());
        pushButton_Task->setText(QCoreApplication::translate("Game_MainPage", "\344\273\273\345\212\241", nullptr));
        pushButton_Shopping->setText(QCoreApplication::translate("Game_MainPage", "\347\233\264\345\224\256\345\225\206\345\237\216", nullptr));
        pushButton_Choujiang->setText(QCoreApplication::translate("Game_MainPage", "\351\205\222\351\246\206\346\212\275\345\245\226", nullptr));
        pushButton_Pet->setText(QCoreApplication::translate("Game_MainPage", "\345\256\240\347\211\251", nullptr));
        pushButton_Store->setText(QCoreApplication::translate("Game_MainPage", "\350\227\217\345\223\201", nullptr));
        pushButton_PrepareForWar->setText(QCoreApplication::translate("Game_MainPage", "\345\244\207\346\210\230", nullptr));
        pushButton_13->setText(QCoreApplication::translate("Game_MainPage", "\351\231\220\346\227\266\346\264\273\345\212\250", nullptr));
        pushButton_SendChatmsg->setText(QCoreApplication::translate("Game_MainPage", "\345\217\221\351\200\201", nullptr));
        lineEdit_ChatmsgMychat->setText(QCoreApplication::translate("Game_MainPage", "\350\257\264\347\202\271\344\273\200\344\271\210\345\220\247", nullptr));
        pushButton_ShowChatMsg->setText(QCoreApplication::translate("Game_MainPage", "\346\230\276\347\244\272\346\266\210\346\201\257", nullptr));
        pushButton_ChatTouxiang1->setText(QString());
        pushButton_ChatTouxiang2->setText(QString());
        pushButton_ChatTouxiang3->setText(QString());
        pushButton_ChatTouxiang4->setText(QString());
        pushButton_ChatTouxiang1_2->setText(QString());
        pushButton_ChatTouxiang2_2->setText(QString());
        pushButton_ChatTouxiang3_2->setText(QString());
        pushButton_ChatTouxiang4_2->setText(QString());
        pushButton_ChatTouxiang5->setText(QString());
        pushButton_ChatTouxiang6->setText(QString());
        pushButton_ChatTouxiang5_2->setText(QString());
        pushButton_ChatTouxiang6_2->setText(QString());
        pushButton_CreateRoom->setText(QCoreApplication::translate("Game_MainPage", "\345\210\233\345\273\272\346\210\277\351\227\264", nullptr));
        pushButton_Join_Room->setText(QCoreApplication::translate("Game_MainPage", "\345\212\240\345\205\245\346\210\277\351\227\264", nullptr));
        pushButton_JoinRandomRoom->setText(QCoreApplication::translate("Game_MainPage", "\351\232\217\346\234\272\345\212\240\345\205\245", nullptr));
        pushButton_Room_back->setText(QCoreApplication::translate("Game_MainPage", "\350\277\224\345\233\236", nullptr));
        label_CreateRoomName->setText(QCoreApplication::translate("Game_MainPage", "\350\257\267\350\276\223\345\205\245\350\246\201\345\210\233\345\273\272\347\232\204\346\210\277\351\227\264\345\220\215", nullptr));
        label_CreateRoomFlag->setText(QCoreApplication::translate("Game_MainPage", "\350\257\267\350\276\223\345\205\245\350\246\201\345\210\233\345\273\272\347\232\204\346\210\277\351\227\264\347\261\273\345\236\213", nullptr));
        label_CreateRoomPasswd->setText(QCoreApplication::translate("Game_MainPage", "\346\210\277\351\227\264\345\257\206\347\240\201", nullptr));
        label_CreateRoomDescription->setText(QCoreApplication::translate("Game_MainPage", "\346\210\277\351\227\264\347\256\200\344\273\213", nullptr));
        pushButton_CreateRoomShow->setText(QCoreApplication::translate("Game_MainPage", "\345\210\233\345\273\272\346\210\277\351\227\264", nullptr));
        pushButton_CreateRoomBack->setText(QCoreApplication::translate("Game_MainPage", "\345\217\226\346\266\210\345\210\233\345\273\272", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Game_MainPage: public Ui_Game_MainPage {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_GAME_MAINPAGE_H
